cmake_minimum_required(VERSION 3.14)
project(TestGrpc)
set(CMAKE_CXX_STANDARD 17)
find_package(gRPC)
if (gRPC_FOUND)
  message(STATUS "gRPC found!")
else()
  message(STATUS "gRPC NOT found!")
endif()
